"""Hand-written seed corpus for the local intent classifier.

Everything here is authored in-repo: the classifier is trained offline at
startup from this list, so the bot never needs a network call or an API key to
recognise intent. Labels must stay in sync with `app.agents.router.Intent`.
"""

from __future__ import annotations

INTENT_LABELS: tuple[str, ...] = (
    "order_tracking",
    "returns",
    "shipping",
    "recommendations",
    "handoff",
    "menu",
    "fallback",
)


TRAINING_EXAMPLES: dict[str, list[str]] = {
    "order_tracking": [
        "where is my order",
        "where's my order right now",
        "track my order please",
        "i want to track my package",
        "what's the status of my order",
        "order status",
        "my parcel hasn't turned up",
        "my package never arrived",
        "i haven't received my delivery yet",
        "can you tell me where my shipment is",
        "any update on my order",
        "has my order left the warehouse yet",
        "i want to check on an order i placed",
        "when will my order arrive",
        "is my order on its way",
        "i need tracking info for my purchase",
        "did my order ship yet",
        "my delivery is running late",
        "where's my stuff",
        "locate my package",
        "check order number 111",
        "i placed an order last week and heard nothing",
        "tracking number for my order",
        "my box hasn't shown up",
        "look up my order for me",
    ],
    "returns": [
        "what is your return policy",
        "i want to return this",
        "how do i send it back",
        "can i exchange this jacket",
        "i'd like my money back",
        "i want a refund",
        "this doesn't fit, can i swap it",
        "how long do i have to return an item",
        "return policy details",
        "can i get a refund on my purchase",
        "i need to send back a tent",
        "do you accept returns",
        "the boots are the wrong size, what are my options",
        "how do returns work",
        "i changed my mind about my purchase",
        "can i return something i never used",
        "start a return for me",
        "what's your exchange policy",
        "i want to give this back for store credit",
        "is there a restocking fee for returns",
        "refund request",
        "i'd like to return an unused item in its original box",
        "returns and exchanges",
        "how many days do i have to return gear",
    ],
    "shipping": [
        "how long does shipping take",
        "what are your delivery times",
        "how quickly can you get it to me",
        "do you offer expedited shipping",
        "what shipping options do you have",
        "how fast is standard shipping",
        "how long is standard shipping",
        "what's the difference between standard and expedited",
        "how many business days for delivery",
        "can i pay to get it faster",
        "delivery timeframe",
        "do you ship to canada",
        "shipping information please",
        "how soon would an order arrive if i buy today",
        "what's your shipping policy",
        "is overnight shipping available",
        "typical delivery window",
        "shipping speed",
        "when do you dispatch orders",
        "how much time for expedited delivery",
        "do you ship internationally",
        "what shipping methods are available",
        "tell me about delivery costs and speeds",
    ],
    "recommendations": [
        "can you recommend a sleeping bag",
        "what's the best tent for two people",
        "i'm looking for winter camping gear",
        "i need boots for hiking",
        "what do you suggest for sub-zero temperatures",
        "help me pick a jacket",
        "which sleeping bag should i buy",
        "any suggestions for family car camping",
        "what gear do i need for a weekend backpacking trip",
        "show me your tents",
        "i want something warm for cold hikes",
        "best product for backcountry cooking",
        "what would you recommend for a beginner camper",
        "i need a camp stove",
        "looking for a budget friendly sleeping bag",
        "which jacket is warmest",
        "recommend some footwear for rugged trails",
        "what should i buy for a 3-season trip",
        "do you have a 4 person tent",
        "i need gear for freezing weather",
        "product recommendations please",
        "what's good for backpacking",
        "help me choose between your sleeping bags",
        "what's the best sleeping bag for sub-zero temperatures",
        "another recommendation",
        "give me a different recommendation please",
        "any other recommendation for camp kitchen or apparel",
        "show me footwear options",
    ],
    "handoff": [
        "talk to a human",
        "i want to speak to a person",
        "connect me with an agent",
        "put me through to someone",
        "can i get a real person please",
        "live agent",
        "transfer me to customer service",
        "i need to speak with a representative",
        "get me a human being",
        "this bot isn't helping, i want a person",
        "let me talk to support staff",
        "escalate this to someone",
        "i'd like to chat with an employee",
        "human please",
        "can someone from your team help me",
        "i want to talk to a manager",
        "please connect me to customer support",
        "hand me off to an advisor",
        "operator",
        "i need real help from a person",
        "is anyone there i can speak with",
    ],
    "menu": [
        "main menu",
        "menu",
        "start over",
        "go back",
        "return to the bot",
        "back to the bot",
        "hi",
        "hello",
        "hey there",
        "what can you do",
        "show me my options",
        "take me back to the beginning",
        "restart",
        "help",
        "what are my choices",
        "list the options",
        "back to main menu",
        "reset this conversation",
        "start again",
        "good morning",
        "i want the bot again",
        "give me the bot back",
        "can i go back to the bot",
        "put me back with the bot please",
    ],
    "fallback": [
        "asdfgh qwerty",
        "zxcvbn",
        "qwertyuiop",
        "blah blah blah",
        "asdf",
        "lorem ipsum dolor",
        "what's the weather like tomorrow",
        "do you sell cars",
        "tell me a joke",
        "who won the game last night",
        "what is the capital of france",
        "can you write me a poem",
        "flurble wonk zip",
        "1234567890",
        "do you give tax advice",
        "sing me a song",
        "what's your favourite colour",
        "hjkl hjkl",
        "random nonsense words here",
        "how do i fix my car engine",
        "book me a flight to denver",
        "banana telephone rocket",
        "xyzzy plugh",
        "purple monkey dishwasher",
        "kdjfhg lskdjfh",
        "please",
        "okay",
        "ok thanks",
        "thank you",
        "i don't know",
        "no idea",
        "maybe later",
    ],
}


def flatten() -> tuple[list[str], list[str]]:
    """Return (texts, labels) in a stable order."""
    texts: list[str] = []
    labels: list[str] = []
    for label in INTENT_LABELS:
        for text in TRAINING_EXAMPLES[label]:
            texts.append(text)
            labels.append(label)
    return texts, labels
